'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.8669
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.CompactFramework.Design.Data generó automáticamente este código fuente, versión=2.0.50727.8669.
'
Namespace OxigenosWS
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="DataAccessSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DataAccess
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://192.168.0.24/WebServicesOBC/DataAccess.asmx"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFechaSistema", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetFechaSistema() As String
            Dim results() As Object = Me.Invoke("GetFechaSistema", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetFechaSistema(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetFechaSistema", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetFechaSistema(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDatosCarga", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDatosCarga(ByVal sTerminal As String, ByVal iCodigoProceso As Integer, ByVal iCodigoPrograma As Integer) As String
            Dim results() As Object = Me.Invoke("GetDatosCarga", New Object() {sTerminal, iCodigoProceso, iCodigoPrograma})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetDatosCarga(ByVal sTerminal As String, ByVal iCodigoProceso As Integer, ByVal iCodigoPrograma As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetDatosCarga", New Object() {sTerminal, iCodigoProceso, iCodigoPrograma}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetDatosCarga(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmarCarga", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub ConfirmarCarga(ByVal sTerminal As String, ByVal iCodigoProceso As Integer, ByVal iCodigoPrograma As Integer)
            Me.Invoke("ConfirmarCarga", New Object() {sTerminal, iCodigoProceso, iCodigoPrograma})
        End Sub
        
        '''<remarks/>
        Public Function BeginConfirmarCarga(ByVal sTerminal As String, ByVal iCodigoProceso As Integer, ByVal iCodigoPrograma As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ConfirmarCarga", New Object() {sTerminal, iCodigoProceso, iCodigoPrograma}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndConfirmarCarga(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendDatos", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub SendDatos(ByVal sTerminal As String, ByVal iCodigoPrograma As Integer, ByVal iCodigoProceso As Integer, ByVal sDatosEnviados As String)
            Me.Invoke("SendDatos", New Object() {sTerminal, iCodigoPrograma, iCodigoProceso, sDatosEnviados})
        End Sub
        
        '''<remarks/>
        Public Function BeginSendDatos(ByVal sTerminal As String, ByVal iCodigoPrograma As Integer, ByVal iCodigoProceso As Integer, ByVal sDatosEnviados As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendDatos", New Object() {sTerminal, iCodigoPrograma, iCodigoProceso, sDatosEnviados}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndSendDatos(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
    End Class
End Namespace
